# Created with YamlCreate.ps1 v2.4.1 $debug=QUSU.CRLF.7-4-6.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Perforce.P4V
PackageVersion: 242.43.4
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerSwitches:
  Silent: /s
  SilentWithProgress: /passive
  Custom: /norestart
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://www.perforce.com/downloads/perforce/r24.3/bin.ntx64/p4vinst64.msi
  InstallerSha256: F1DF73CD3158344388D9042C336F837F6CFFE5BF68CF2D69BF8C6EAFF6ACDE72
  ProductCode: '{4307B5A9-1CE8-4208-BA96-E4D2787E624B}'
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://www.perforce.com/downloads/perforce/r24.3/bin.ntx64/p4vinst64.exe
  InstallerSha256: 92089AFD6F9D688BEBBB3D3483B6FDA243D3EA40DCF5CD680CCECCEB3FAAE6B7
  ProductCode: '{09BBE8EC-6AC2-400E-8220-89AD3E3EFDB6}'
ManifestType: installer
ManifestVersion: 1.6.0
